version: "3.9"
services:
  app:
#    image: registry.gurdil.fr:4443/site_vote:v1.0-amd64
    build: .
    ports:
      - "80:80"
    environment:
      ENV: "deployed"
      DOMAIN: "site-vote.rag-cloud.hosteur.com"
      DATABASE_URL: "postgresql://root:plopplop@database/sitevote"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: plopplop
      POSTGRES_USER: root
      POSTGRES_DB: sitevote