version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - ENV=deployed
      - DOMAIN=grotte-juniors.rag-cloud.hosteur.com
      - DATABASE_URL=postgresql://root:plopplop@database/sitevote
    depends_on:
      database:
        condition: service_started

  database:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: plopplop
      POSTGRES_USER: root
      POSTGRES_DB: sitevote