version: "3.9"
services:
  app:
    image: registry.gurdil.fr:4443/site_vote:v1.0-amd64
    ports:
      - "8000:5000"
    environment:
      DOMAIN: "site-vote.rag-cloud.hosteur.com"
      DATABASE_URL: "postgresql://root:plopplop@database/sitevote"

  database:
    image: "postgres:15.2"
    restart: always
    environment:
      POSTGRES_PASSWORD: plopplop
      POSTGRES_USER: root
      POSTGRES_DB: sitevote